### ISSUE TITLE
Add Table of Contents to explanations page

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/Prolangle#113]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I can't find what I look for on the explanations page.

### Describe the solution you'd like

I would like to see a table of contents so I can easily navigate there.

### Additional context

I like how Wikipedia has a sticky ToC:
![image](https://github.com/ricardoboss/Prolangle/assets/6266356/539c4df4-ea1c-4a3c-90e1-f37ea509c23b)

**Comment by chucker** [comment]
Maybe see https://github.com/Megabit/Blazorise/blob/master/Documentation/Blazorise.Docs/Components/Toc.razor
