### ISSUE TITLE
Daily seed?

### ISSUE THREAD

**Issue by chucker** [ricardoboss/Prolangle#2]
Right now, randomness gets seeded on startup. We probably want a deterministic (but not guessable?) way to get a day's game, so that people can play it in sync.

**Comment by ricardoboss** [comment]
So this is essentially fixed then? The current solution produces the same results every year, but we are fine for now.

**Comment by chucker** [comment]
Yes, this is IMHO fixed, but I do agree `GuessGame` needs a redesign. I'm not sure where to continue that conversation, but it technically doesn't belong here.
