### ISSUE TITLE
Remove boilerplate

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/Prolangle#55]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to click on the Languages nav entry and the other pages are useless

### Describe the solution you'd like

I would like the Languages page to be the homepage and the other pages removed

**Comment by chucker** [comment]
I don’t love the sidebar. Can we make the two games two tabs? And the explanations page a link at the bottom?

**Comment by ricardoboss** [comment]
Along with this, we could also introduce some ✨ style ✨
