### ISSUE TITLE
[Bug]: Table does not scroll when screen is narrow

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/Prolangle#81]
### What happened?

The table is cut off when its wider than the current screen.

### Screenshots

<img width="712" alt="image" src="https://github.com/ricardoboss/Prolangle/assets/6266356/89cd18c7-1e53-483f-a91c-30cc3270dc99">

**Comment by chucker** [comment]
The hover effect is there, but it's not really responsive, is it? It just scrolls horizontally.
