### ISSUE TITLE
Code Snippets Game

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/Prolangle#9]
We'd like to add a second game mode where the goal is to guess a programming language with a (partially revealed) code snippet.

Ideally, each language available has one or more code snippets available. This way players will rarely get the same snippets more than once or twice.

The code snippet is mostly concealed at the beginning and gets revealed with each wrong guess, so it gets easier the more wrong guesses are made. At the end, the whole snippet, maybe with filename and extension, is revealed.

The revealing algorithm should be able to work with arbitrary code snippets from all supported languages. It could use percentages or tokens to determine what parts to reveal.

**Comment by chucker** [comment]
Idea: don’t start from the middle each time. Randomize so it starts somewhere between 20 and 80% of the code, or something.

**Comment by chucker** [comment]
#70 status:

- [x] conceal feature 
- [x] jitter
- [x] a bunch of snippets to play with
- [ ] linked from navigation
- [ ] show filename and extension
- [ ] many, many more snippets
- [ ] show attribution

I would like if we could move the bottom three to a separate PR.

**Comment by ricardoboss** [comment]
I think the only thing I would include in #70 is the filename and extension. All other tasks (especially the "many, many more snippets") should be handled in separate issues.

We could either expand the list in #7 to also track missing snippets for languages or create a new pinned issue with a different list only for snippets.

**Comment by chucker** [comment]
> We could either expand the list in #7 to also track missing snippets for languages or create a new pinned issue with a different list only for snippets.

#90
